version: "3.8"
services:
  backend:
    build: .
    container_name: backend_container
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
      - redis
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/crud_app
      - JWT_SECRET=your_jwt_secret
      - REDIS_HOST=redis_container
      - REDIS_PORT=6379
    volumes:
      - .:/app
    networks:
      - backend-network

  mongodb:
    image: mongo
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend-network

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend-network
    command: redis-server --appendonly yes

volumes:
  mongodb_data:

networks:
  backend-network:
    driver: bridge
